spring:
  profiles: default

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ENC(fDr+GDJpLXX/Ko0Emq+c/WDhmLO00egIE/JnTBfBTIIGbx5Lk7mehOTFHm+wjcZHcL5dI9WoI5m9N1CqWUKVTzPPYbssyclKQZ2fiYeVLCQXeXyohJGdhi49rTNhv9eLx78qKumPvozR2UJG9v7KHTyxSKKX+JTkv5KCHLqNiz0f7IsW09YrK5ZP1AC5qZlLw6FEAhSc8BzlndMvprb8oxMXso1vOs8w)
    username: ENC(8SqjzYv8l7gDHILm8cETrA==)
    password: ENC(2LwLaEh2R+jWjEMb1rQ8mJFshzlma+P4)
    
  http:
    encoding:
      charset: UTF-8

jasypt:
  encryptor:
    bean: jasyptStringEncrptor
    password: SENIER_PROJECT

server:
  port: 80
