spring:
  profiles: default

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ENC(GWOhdcDeqr+8zSiWsPrAntKLOEZnSS5S9X+3CJNuH2B8yE7OLIp6VercRzPeTQnMzKCD481PM1XK2SKiDwa2YRhItIKTA6GP/treeObvs5aUIc7jYt1/1AVodqlfoeCb8Cb0vchhJhSWuRgjMOp90yoE6+vkUkfMIMAa4cbAEgNfSR7zTv5+5abOnglkvAjEPYlP1nHhP1QdzckODk+ezkowUOnkREGI)
    username: ENC(pQcgjPuN48cNrtV86X0KyQ==)
    password: ENC(3xVDuwiZYRyM8eudVS7EyQ==)
    
  http:
    encoding:
      charset: UTF-8

jasypt:
  encryptor:
    bean: jasyptStringEncrptor

server:
  port: 8092